name: run-r-iris
on:
  push: 
    branches:
      - main
    paths:
      - .github/**
      - workflows/r/iris/**
  pull_request:
    branches:
      - main
    paths:
      - workflows/r/iris/**
      - .github/**
  #schedule:
  #    - cron: "0 0/2 * * *"
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with: 
        python-version: "3.8"
    #- name: pip install
    #  run: pip install -r requirements.txt
    #  To dwonload correct version
    #- name: downlaod az ml cli v2
    #  run:  curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash 
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_CREDS}}
    - name: install az ml cli v2
      run: az extension add -n ml -y

    - name: attach workspace
      run: az configure --defaults group="helenloll" workspace="helenloll"
    - name: run basic job
      run: az ml job create -f workflows/r/iris/job.yml --web
